[package]
name = "Horizon-API"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2", features = ["sqlite"] }
dotenv = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
diesel_migrations = "2"